spring:
  application:
    name: gateway-service

  reactor:
    context-propagation: auto

  cloud:
    gateway:
      server:
        web flux:
          routes:
            - id: users-service
              uri: http://localhost:8081
              predicates:
                - Path=/users, /users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: users-service
                    fallbackUri: forward:/fallback/users

resilience4j:
  circuitbreaker:
    instances:
      users-service:
        sliding-window-size: 10
        failure-rate-thereshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slidingWindowType: COUNT_BASED

management:
  zipkin:
    tracing:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: gateway-service-java

server:
  port: 8080